workflows

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,39 +1,180 @@
-name: Project Build
-run-name: "Project Build #${{ github.run_number }}"
-
+name: Project Info
+run-name: "Project Info #${{ github.run_number }}"
 on:
-  workflow_call:
-    inputs:
-      project_version:
-        required: true
-        type: string
-      project_name:
-        required: true
-        type: string
-      project_full_name:
-        required: true
-        type: string
-      changelog:
-        required: true
-        type: string
-      diff:
-        required: true
-        type: string
-      release_type:
-        required: true
-        type: string
-      minecraft_version:
-        required: true
-        type: string
+  push:
+    branches:
+      - main
 
 concurrency:
   group: ${{ github.workflow }}
   cancel-in-progress: true
 
-jobs:
+env:
+  RELEASE_TYPE: "release"
+  MINECRAFT_VERSION: "1.12.2"
+
+jobs:    
+  info:
+    name: 🖥️ Project Info
+    runs-on: ubuntu-latest
+    outputs:
+      project_version: ${{ steps.project_version.outputs.tag }}
+      project_name: ${{ steps.project_name.outputs.value }}
+      project_full_name: ${{ steps.project_name.outputs.value }}-${{ steps.project_version.outputs.tag }}
+      changelog: ${{ steps.changelog.outputs.description }}
+      diff: ${{ steps.read_diff.outputs.diff }}
+      release_type: ${{ env.RELEASE_TYPE }}
+      minecraft_version: ${{ env.MINECRAFT_VERSION }}
+      exists: ${{ steps.check_tag.outputs.exists }}
+    
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4.2.2
+        with:
+          fetch-depth: 0
+        
+      - name: 🔍 Check pakku-lock.json
+        id: check_pakku_lock
+        shell: bash
+        run: |
+          if [ ! -f pakku-lock.json ]; then
+            echo "❌ Could not find pakku-lock.json" && exit 1
+          else
+            echo "✔️ pakku-lock.json"
+          fi
+        
+      - name: 🔍 Check pakku.json
+        id: check_pakku
+        shell: bash
+        run: |
+          if [ ! -f pakku.json ]; then
+            echo "❌ Could not find pakku.json" && exit 1
+          else
+            echo "✔️ pakku.json"
+          fi
+        
+      - name: 📈 Get latest tag
+        id: latest_tag
+        shell: bash
+        run: |
+          tag=$(git describe --tags --abbrev=0)
+          if [ -z "$tag" ]; then
+            echo "❌ Latest tag not found" && exit 1
+          else
+            echo "✔️ Latest tag found: $tag"
+            echo "tag=$tag" >> $GITHUB_OUTPUT
+          fi
+        
+      - name: 🔍 Check pakku-lock.json in previous tag
+        id: check_pakku_lock_prev
+        shell: bash
+        run: |
+          if ! git ls-tree -r ${{ steps.latest_tag.outputs.tag }} -- ./pakku-lock.json &> /dev/null; then
+            echo "❌ File pakku-lock.json not found in previous tag" && exit 1
+          else
+            echo "✔️ File pakku-lock.json found in previous tag"
+          fi
+        
+      - name: 📁 Copy pakku-lock.json from previous tag
+        id: copy_pakku_lock_prev
+        shell: bash
+        run: |
+          git show tags/${{ steps.latest_tag.outputs.tag }}:./pakku-lock.json > ./pakku-lock-prev.json
+          if [ -s ./pakku-lock-prev.json ]; then
+            echo "✔️ File pakku-lock-prev.json created"
+          else
+            echo "❌ Error: File pakku-lock-prev.json is empty or not created" && exit 1
+          fi
+        
+      - name: 📦 Download pakku.jar
+        id: download_pakku
+        shell: bash
+        run: |
+          curl https://github.com/juraj-hrivnak/pakku/releases/latest/download/pakku.jar -o pakku.jar -L -J
+          echo "✔️ Downloaded pakku.jar "
+        
+      - name: 🔄 Run pakku diff
+        id: pakku_diff
+        shell: bash
+        run: |
+          java -jar pakku.jar diff -v --markdown PROJECTS_DIFF.md ./pakku-lock-prev.json ./pakku-lock.json
+          if [ -f PROJECTS_DIFF.md ]; then
+            echo "✔️ Comparison completed"
+          else
+            echo "❌ Error: File PROJECTS_DIFF.md not created" && exit 1
+          fi
+        
+      - name: 📝 Read PROJECTS_DIFF.md to variable
+        id: read_diff
+        shell: bash
+        run: |
+          echo "📝 Reading PROJECTS_DIFF.md to variable..."
+          {
+            echo 'diff<<EOF'
+            cat -v PROJECTS_DIFF.md
+            echo EOF
+          } >> "$GITHUB_OUTPUT"
+          echo "✔️ Diff content read to variable"
+        
+      - name: 📊 Get Project Name
+        id: project_name
+        uses: ActionsTools/read-json-action@v1.0.5
+        with:
+          file_path: "pakku.json"
+          prop_path: "name"
+        
+      - name: 📊 Get Project Version
+        id: project_version
+        uses: ActionsTools/read-json-action@v1.0.5
+        with:
+          file_path: "pakku.json"
+          prop_path: "version"
+
+      - name: 📊 Get Minecraft Version
+        id: minecraft_version
+        uses: ActionsTools/read-json-action@v1.0.5
+        with:
+          file_path: "pakku-lock.json"
+          prop_path: "mc_versions"
+        
+      - name: 📄 Changelog Parser
+        id: changelog
+        uses: coditory/changelog-parser@v1.0.2
+        with:
+          path: CHANGELOG.md
+        
+      - name: 📈 Upload Diff
+        id: upload_diff
+        if: ${{ steps.read_diff.outputs.diff != '' }}
+        uses: actions/upload-artifact@v4.4.3
+        with:
+          name: Mods-diff
+          path: PROJECTS_DIFF.md
+        
+      - name: 🔍 Check if tag exists
+        uses: mukunku/tag-exists-action@v1.6.0
+        id: check_tag
+        with:
+          tag: ${{ steps.project_version.outputs.value }}
+        
+      - name: 📝 Generate Github Summary
+        run: |
+          echo "📃 **Name**: ${{ steps.project_name.outputs.value }}" >> $GITHUB_STEP_SUMMARY
+          echo "📃 **Release**: ${{ steps.project_version.outputs.value }}" >> $GITHUB_STEP_SUMMARY
+          echo "📃 **Release Type**: ${{ env.RELEASE_TYPE }}" >> $GITHUB_STEP_SUMMARY
+          echo "📃 **Game Version**: ${{ env.MINECRAFT_VERSION }}" >> $GITHUB_STEP_SUMMARY
+          
+          echo "${{ steps.changelog.outputs.description }}" >> $GITHUB_STEP_SUMMARY
+          if [ -n "${{ steps.read_diff.outputs.diff != '' }}" ]; then
+            echo "${{ steps.read_diff.outputs.diff }}" >> $GITHUB_STEP_SUMMARY
+          fi
+  
+
   build-modpack:
     name: Build Modpack
+    needs: [info]
     runs-on: ubuntu-latest
+    if: needs.info.outputs.exists != 'true'
 
     steps:
       - name: Checkout
@@ -47,7 +188,7 @@ jobs:
           grooovy="./groovy/runConfig.json"
           cat <<< $(jq '.debug = false' $grooovy) > $grooovy
 
-          VERSION=${{ inputs.project_version }}
+          VERSION=${{ needs.info.outputs.project_version }}
           sed -i -e "s/DEV/${VERSION}/g" pakku.json
           sed -i -e "s/DEV/${VERSION}/g" config/fancymenu/customization/gui_main_menu.txt
 
@@ -71,8 +212,8 @@ jobs:
       - name: Upload artifact CurseForge
         uses: actions/upload-artifact@v4.4.3
         with:
-          name: ${{ inputs.project_full_name }}-curseforge
-          path: ./build/curseforge/${{ inputs.project_full_name }}-curseforge.zip
+          name: ${{ needs.info.outputs.project_full_name }}-curseforge
+          path: ./build/curseforge/${{ needs.info.outputs.project_full_name }}-curseforge.zip
           if-no-files-found: error
 
       - name: Rename artifact modrinth
@@ -83,13 +224,15 @@ jobs:
       - name: Upload artifact modrinth
         uses: actions/upload-artifact@v4.4.3
         with:
-          name: ${{ inputs.project_full_name }}-modrinth
-          path: ./build/modrinth/${{ inputs.project_full_name }}-modrinth.mrpack
+          name: ${{ needs.info.outputs.project_full_name }}-modrinth
+          path: ./build/modrinth/${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
           if-no-files-found: warn
 
   build-server:
-    name: Build Server Pack
+    name: Build Server
+    needs: [info]
     runs-on: ubuntu-latest
+    if: needs.info.outputs.exists != 'true'
 
     steps:
       - name: Checkout
@@ -103,7 +246,7 @@ jobs:
           grooovy="./groovy/runConfig.json"
           cat <<< $(jq '.debug = false' $grooovy) > $grooovy
 
-          VERSION=${{ inputs.project_version }}
+          VERSION=${{ needs.info.outputs.project_version }}
           sed -i -e "s/DEV/${VERSION}/g" pakku.json
           sed -i -e "s/DEV/${VERSION}/g" config/fancymenu/customization/gui_main_menu.txt
 
@@ -128,13 +271,15 @@ jobs:
       - name: Upload artifact server
         uses: actions/upload-artifact@v4.4.3
         with:
-          name: ${{ inputs.project_full_name }}-serverpack
-          path: ./build/serverpack/${{ inputs.project_full_name }}-serverpack.zip
+          name: ${{ needs.info.outputs.project_full_name }}-serverpack
+          path: ./build/serverpack/${{ needs.info.outputs.project_full_name }}-serverpack.zip
           if-no-files-found: error
 
   build-multimc:
-    name: Build MultiMC Pack
+    name: Build MultiMC
+    needs: [info]
     runs-on: ubuntu-latest
+    if: needs.info.outputs.exists != 'true'
     
     steps:
       - name: Checkout
@@ -148,7 +293,7 @@ jobs:
           grooovy="./groovy/runConfig.json"
           cat <<< $(jq '.debug = false' $grooovy) > $grooovy
 
-          VERSION=${{ inputs.project_version }}
+          VERSION=${{ needs.info.outputs.project_version }}
           sed -i -e "s/DEV/${VERSION}/g" pakku.json
           sed -i -e "s/DEV/${VERSION}/g" config/fancymenu/customization/gui_main_menu.txt
           sed -i -e "s/DEV/${VERSION}/g" .pakku/multimc-overrides/instance.cfg
@@ -175,25 +320,163 @@ jobs:
           mv -vf ./mods .pakku/multimc-overrides/.minecraft/mods
           cd .pakku/multimc-overrides/
           
-          zip -r ${{ inputs.project_full_name }}-multimc.zip icon.png mmc-pack.json instance.cfg .minecraft/ flame/
+          zip -r ${{ needs.info.outputs.project_full_name }}-multimc.zip icon.png mmc-pack.json instance.cfg .minecraft/ flame/
       
       - name: Upload zip multimc
         uses: actions/upload-artifact@v4.4.3
         with:
-          name: ${{ inputs.project_full_name }}-multimc
-          path: .pakku/multimc-overrides/${{ inputs.project_full_name }}-multimc.zip
+          name: ${{ needs.info.outputs.project_full_name }}-multimc
+          path: .pakku/multimc-overrides/${{ needs.info.outputs.project_full_name }}-multimc.zip
           if-no-files-found: error
 
+  release-curseforge:
+    name: Release to CurseForge
+    needs: [info, build-modpack, build-server]
+    runs-on: ubuntu-latest
+    outputs:
+      id: ${{ steps.release.outputs.id }}
 
-  release:
-    needs: [build-modpack, build-server, build-multimc]
-    uses: ./.github/workflows/release.yml
-    with:
-      project_version: ${{ inputs.project_version }}
-      project_name: ${{ inputs.project_name }}
-      project_full_name: ${{ inputs.project_full_name }}
-      changelog: ${{ inputs.changelog }}
-      diff: ${{ inputs.diff }}
-      release_type: ${{ inputs.release_type }}
-      minecraft_version: ${{ inputs.minecraft_version }}
-    secrets: inherit
+    steps:
+      - name: Check if CURSEFORGE_TOKEN exist
+        shell: bash
+        run: |
+          if [ "${{ secrets.CURSEFORGE_TOKEN }}" == '' ]; then
+            echo '::error::No value found for secret key `CURSEFORGE_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+          fi  
+
+      - name: Download artifact curseforge
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: ${{ needs.info.outputs.project_full_name }}-curseforge
+
+      - name: Download artifact server
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: ${{ needs.info.outputs.project_full_name }}-serverpack
+
+      - name: Upload Curseforge
+        id: release
+        uses: Xikaro/upload-curseforge-modpack-action@1.1.1
+        with:
+          api-token: ${{ secrets.CURSEFORGE_TOKEN }}
+          project-id: ${{ vars.CURSEFORGE_ID }}
+          display-name: ${{ needs.info.outputs.project_full_name }}
+          modpack-path: ${{ needs.info.outputs.project_full_name }}-curseforge.zip
+          server-display-name: ${{ needs.info.outputs.project_full_name }}-serverpack
+          modpack-server-path: ${{ needs.info.outputs.project_full_name }}-serverpack.zip
+          changelog: |
+            ${{ needs.info.outputs.changelog }}
+            ${{ needs.info.outputs.diff }}
+          changelog-format: markdown
+          game-version: ${{ needs.info.outputs.minecraft_version }}
+          release-type: ${{ needs.info.outputs.release_type }}
+
+  release-modrinth:
+      name: Release to Modrinth
+      needs: [info, build-modpack, build-server]
+      runs-on: ubuntu-latest
+
+      steps:
+        - name: Check if MODRINTH_API_TOKEN exist
+          shell: bash
+          run: |
+            if [ "${{ secrets.MODRINTH_TOKEN }}" == '' ]; then
+              echo '::error::No value found for secret key `MODRINTH_TOKEN`. See https://docs.github.com/en/  actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+            fi  
+    
+        - name: Download artifact modrinth
+          uses: actions/download-artifact@v4.1.8
+          with:
+            name: ${{ needs.info.outputs.project_full_name }}-modrinth
+    
+        - name: Download artifact server
+          uses: actions/download-artifact@v4.1.8
+          with:
+            name: ${{ needs.info.outputs.project_full_name }}-serverpack
+    
+        - name: Upload Modrinth
+          id: release
+          uses: Xikaro/upload-curseforge-modpack-action@1.1.1
+          with:
+            api-token: ${{ secrets.MODRINTH_TOKEN }}
+            project-id: ${{ vars.MODRINTH_ID }}
+            modpack-path: ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
+            modpack-server-path: ${{ needs.info.outputs.project_full_name }}-serverpack.zip
+            changelog: ${{ needs.info.outputs.changelog }}
+            changelog-format: markdown
+            game-version: ${{ needs.info.outputs.minecraft_version }}
+            display-name: ${{ needs.info.outputs.project_full_name }}
+            server-display-name: ${{ needs.info.outputs.project_full_name }}-serverpack
+            release-type: ${{ needs.info.outputs.release_type }}
+
+  release-github:
+    name: Release to GitHub
+    needs: [info, build-modpack, build-server, build-multimc]
+    runs-on: ubuntu-latest
+    outputs:
+      url: ${{ steps.release.outputs.url }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4.2.2
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4.1.8
+        with:
+          merge-multiple: true
+
+      - name: Сlose fixed in dev
+        uses: Xikaro/close-issues-based-on-label@master
+        env:
+          LABEL: "2. Status: In Dev"
+          COMMENT: In ${{ needs.info.outputs.project_version }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Create release
+        id: release
+        uses: softprops/action-gh-release@v2.0.9
+        with:
+          name: ${{ needs.info.outputs.project_version }}
+          tag_name: ${{ needs.info.outputs.project_version }}
+          body: |
+            ${{ needs.info.outputs.changelog }}
+            ```markdown
+            ${{ needs.info.outputs.diff }}
+            ```
+          files: |
+            ${{ needs.info.outputs.project_full_name }}-curseforge.zip
+            ${{ needs.info.outputs.project_full_name }}-serverpack.zip
+            ${{ needs.info.outputs.project_full_name }}-multimc.zip
+          prerelease: ${{ needs.info.outputs.release_type != 'release' }}
+          generate_release_notes: true
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+  discord-message:
+    name: Discord Message
+    needs: [info, release-curseforge, release-github]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Truncate Changelog
+        id: truncated
+        uses: cisox/read-more-action@v1.0.2
+        with:
+          text: '${{ needs.info.outputs.changelog }}'
+          max_chars: '1450'
+
+      - name: Send Discord message
+        uses: hugoalh/send-discord-webhook-ghaction@v7.0.2
+        with:
+          key: ${{ secrets.DISCORD_RELEASES }}
+          username: "TerraFirmaGreg"
+          avatar_url: "https://raw.githubusercontent.com/TerraFirmaGreg-Team/.github/main/branding/logo.png"
+          content_links_no_embed: .+
+          content: |
+            **Release**: `${{ needs.info.outputs.project_version }}`
+            **Release Type**: `${{ needs.info.outputs.release_type }}`
+            **Game Version**: `${{ needs.info.outputs.minecraft_version }}`
+
+            [CurseForge](https://www.curseforge.com/minecraft/modpacks/terrafirmagreg-vintage/files/${{ needs.release-curseforge.outputs.id }}) • [GitHub](${{ needs.release-github.outputs.url }}) • [Issues](https://github.com/${{ github.repository }}/issues)
+             ```markdown
+            ${{ steps.truncated.outputs.text  }}
+            - ...```
+            ** [Read more...](${{ needs.release-github.outputs.url }}) **
