workflows

diff --git a/.github/workflows/info.yml b/.github/workflows/info.yml
--- a/.github/workflows/info.yml
+++ b/.github/workflows/info.yml
@@ -23,7 +23,6 @@ jobs:
       project_name: ${{ steps.project_name.outputs.value }}
       project_full_name: ${{ steps.project_name.outputs.value }}-${{ steps.project_version.outputs.tag }}
       changelog: ${{ steps.changelog.outputs.description }}
-      truncated_changelog: ${{ steps.truncated.outputs.text }}
       diff: ${{ steps.lockfile.outputs.diff }}
       release_type: ${{ env.RELEASE_TYPE }}
       minecraft_version: ${{ env.MINECRAFT_VERSION }}
@@ -33,7 +32,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4.2.2
     
-      - name: Check lockfile
+      - name: Check file
         shell: bash
         run: |
           set +e
@@ -56,27 +55,49 @@ jobs:
           set +e
 
           echo "🔎 Getting previous lockfile..."
-          if [ "$latest_tag" = ${{ github.ref_name }} ]; then
-            latest_tag_prev=$(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^)
-            latest_tagged_commit=$(git rev-list -n 1 --pretty=format:"%h" $latest_tag_prev | sed -n 2p)
-    
-            if git cat-file -e $latest_tagged_commit:./pakku-lock.json; then
-              echo "📦 pakku-lock.json found in previous tag"
-              git show $latest_tagged_commit:./pakku-lock.json > ./pakku-lock-prev.json
-              curl https://github.com/juraj-hrivnak/pakku/releases/latest/download/pakku.jar -o pakku.jar -L -J
-              java -jar pakku.jar diff -v --markdown PROJECTS_DIFF.md ./pakku-lock-pre.json ./pakku-lock.json
-            else
-              echo "❌ File pakku-lock.json not found in previous tag"
-            fi
+
+          # Получаем последний тег
+          latest_tag=$(git describe --tags --abbrev=0)
+          if [ -z "$latest_tag" ]; then
+            echo "❌ Latest tag not found"
+            exit 1
           fi
-    
-      - name: Create PROJECTS_DIFF.md
-        shell: bash
-        run: |
-          if [ ! -f PROJECTS_DIFF.md ]; then
-            touch PROJECTS_DIFF.md
-            echo "📝 Created PROJECTS_DIFF.md"
+
+          # Получаем предыдущий тег
+          latest_tag_prev=$(git describe --tags --abbrev=0 $latest_tag^)
+          if [ -z "$latest_tag_prev" ]; then
+            echo "❌ Previous tag not found"
+            exit 1
           fi
+
+          # Получаем хеш коммита, на котором основан предыдущий тег
+          latest_tagged_commit=$(git rev-list -n 1 --pretty=format:"%h" $latest_tag_prev)
+          if [ -z "$latest_tagged_commit" ]; then
+            echo "❌ Latest tagged commit not found"
+            exit 1
+          fi
+
+          # Проверяем, существует ли файл pakku-lock.json в предыдущем теге
+          if ! git cat-file -e $latest_tagged_commit:./pakku-lock.json; then
+            echo "❌ File pakku-lock.json not found in previous tag"
+            exit 1
+          fi
+
+          # Копируем файл pakku-lock.json из предыдущего тега в текущий каталог
+          git show $latest_tagged_commit:./pakku-lock.json > ./pakku-lock-prev.json
+
+          # Качаем последний пакет pakku.jar
+          curl https://github.com/juraj-hrivnak/pakku/releases/latest/download/pakku.jar -o pakku.jar -L -J
+
+          # Получаем хеш текущего файла pakku-lock.json
+          pakku_lock_current=$(git ls-files --error-unmatch ./pakku-lock.json)
+          if [ -z "$pakku_lock_current" ]; then
+            echo "❌ File pakku-lock.json not found in current commit"
+            exit 1
+          fi
+
+          # Выполняем сравнение пакетов с помощью пакета pakku.jar
+          java -jar pakku.jar diff -v --markdown PROJECTS_DIFF.md ./pakku-lock-prev.json ./pakku-lock.json
     
       - name: Format PROJECTS_DIFF.md
         shell: bash
@@ -108,13 +129,6 @@ jobs:
         with:
           path: CHANGELOG.md
 
-      - name: Truncate Changelog
-        id: truncated
-        uses: cisox/read-more-action@v1.0.2
-        with:
-          text: '${{ steps.changelog.outputs.description }}'
-          max_chars: '1450'
-
       - name: Upload Diff
         id: diff
         if: ${{ steps.lockfile.outputs.diff != '' }}
@@ -136,7 +150,7 @@ jobs:
           echo "📃 **Release Type**: ${{ env.RELEASE_TYPE }}" >> $GITHUB_STEP_SUMMARY
           echo "📃 **Game Version**: ${{ env.MINECRAFT_VERSION }}" >> $GITHUB_STEP_SUMMARY
           
-          echo "${{ steps.truncated.outputs.text }}" >> $GITHUB_STEP_SUMMARY
+          echo "${{ steps.changelog.outputs.description }}" >> $GITHUB_STEP_SUMMARY
           if [ -n "${{ steps.lockfile.outputs.diff }}" ]; then
             echo "${{ steps.lockfile.outputs.diff }}" >> $GITHUB_STEP_SUMMARY
           fi
@@ -151,7 +165,6 @@ jobs:
       project_name: ${{ needs.info.outputs.project_name }}
       project_full_name: ${{ needs.info.outputs.project_full_name }}
       changelog: ${{ needs.info.outputs.changelog }}
-      truncated_changelog: ${{ needs.info.outputs.truncated_changelog }}
       diff: ${{ needs.info.outputs.diff }}
       release_type: ${{ needs.info.outputs.release_type }}
       minecraft_version: ${{ needs.info.outputs.minecraft_version }}
