up

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,10 +7,8 @@ env:
 
 on:
   push:
-    branches:
-      - pakku
-    # tags:
-    #   - "*.*.*"
+    tags:
+      - "*.*.*"
 
 concurrency:
   group: ${{ github.ref }}
@@ -253,81 +251,81 @@ jobs:
           path: .pakku/multimc-overrides/${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc.zip
           if-no-files-found: error
 
-  # release-curseforge:
-  #   name: Deploy to CurseForge
-  #   needs: [info, build-modpack, build-server]
-  #   runs-on: ubuntu-latest
-  #   outputs:
-  #     id: ${{ steps.cf_release.outputs.id }}
-  #   steps:
-  #     - name: Check if CF_API_TOKEN exist
-  #       shell: bash
-  #       run: |
-  #         if [ "${{ secrets.CF_API_TOKEN }}" == '' ]; then
-  #           echo '::error::No value found for secret key `CF_API_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
-  #         fi  
+  release-curseforge:
+    name: Deploy to CurseForge
+    needs: [info, build-modpack, build-server]
+    runs-on: ubuntu-latest
+    outputs:
+      id: ${{ steps.cf_release.outputs.id }}
+    steps:
+      - name: Check if CF_API_TOKEN exist
+        shell: bash
+        run: |
+          if [ "${{ secrets.CF_API_TOKEN }}" == '' ]; then
+            echo '::error::No value found for secret key `CF_API_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+          fi  
 
-  #     - name: Download artifact curseforge
-  #       uses: actions/download-artifact@v4.1.8
-  #       with:
-  #         name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge
+      - name: Download artifact curseforge
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge
 
-  #     - name: Download artifact server
-  #       uses: actions/download-artifact@v4.1.8
-  #       with:
-  #         name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
+      - name: Download artifact server
+        uses: actions/download-artifact@v4.1.8
+        with:
+          name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
 
-  #     - name: Upload Curseforge
-  #       id: cf_release
-  #       uses: Xikaro/upload-curseforge-modpack-action@1.1.1
-  #       with:
-  #         api-token: ${{ secrets.CF_API_TOKEN }}
-  #         project-id: ${{ vars.CF_MODPACK_ID }}
-  #         display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}
-  #         modpack-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge.zip
-  #         server-display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
-  #         modpack-server-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
-  #         changelog: ${{ needs.info.outputs.changelog }}
-  #         changelog-format: markdown
-  #         game-version: ${{ needs.info.outputs.mc_version }}
-  #         release-type: ${{ needs.info.outputs.release_type }}
+      - name: Upload Curseforge
+        id: cf_release
+        uses: Xikaro/upload-curseforge-modpack-action@1.1.1
+        with:
+          api-token: ${{ secrets.CF_API_TOKEN }}
+          project-id: ${{ vars.CF_MODPACK_ID }}
+          display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}
+          modpack-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge.zip
+          server-display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
+          modpack-server-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
+          changelog: ${{ needs.info.outputs.changelog }}
+          changelog-format: markdown
+          game-version: ${{ needs.info.outputs.mc_version }}
+          release-type: ${{ needs.info.outputs.release_type }}
 
-  # release-modrinth:
-  #     name: Deploy to Modrinth
-  #     needs: [info, build-modpack, build-server]
-  #     runs-on: ubuntu-latest
-  #     steps:
-  #       - name: Check if MODRINTH_API_TOKEN exist
-  #         shell: bash
-  #         run: |
-  #           if [ "${{ secrets.MODRINTH_API_TOKEN }}" == '' ]; then
-  #             echo '::error::No value found for secret key `MODRINTH_API_TOKEN`. See https://docs.github.com/en/  actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
-  #           fi  
+  release-modrinth:
+      name: Deploy to Modrinth
+      needs: [info, build-modpack, build-server]
+      runs-on: ubuntu-latest
+      steps:
+        - name: Check if MODRINTH_API_TOKEN exist
+          shell: bash
+          run: |
+            if [ "${{ secrets.MODRINTH_API_TOKEN }}" == '' ]; then
+              echo '::error::No value found for secret key `MODRINTH_API_TOKEN`. See https://docs.github.com/en/  actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+            fi  
     
-  #       - name: Download artifact modrinth
-  #         uses: actions/download-artifact@v4.1.8
-  #         with:
-  #           name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-modrinth
+        - name: Download artifact modrinth
+          uses: actions/download-artifact@v4.1.8
+          with:
+            name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-modrinth
     
-  #       - name: Download artifact server
-  #         uses: actions/download-artifact@v4.1.8
-  #         with:
-  #           name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
+        - name: Download artifact server
+          uses: actions/download-artifact@v4.1.8
+          with:
+            name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
     
-  #       - name: Upload Modrinth
-  #         id: cf_release
-  #         uses: Xikaro/upload-curseforge-modpack-action@1.1.1
-  #         with:
-  #           api-token: ${{ secrets.MODRINTH_API_TOKEN }}
-  #           project-id: ${{ vars.MODRINTH_MODPACK_ID }}
-  #           modpack-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-modrinth.mrpack
-  #           modpack-server-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
-  #           changelog: ${{ needs.info.outputs.changelog }}
-  #           changelog-format: markdown
-  #           game-version: ${{ needs.info.outputs.mc_version }}
-  #           display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}
-  #           server-display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
-  #           release-type: ${{ needs.info.outputs.release_type }}
+        - name: Upload Modrinth
+          id: cf_release
+          uses: Xikaro/upload-curseforge-modpack-action@1.1.1
+          with:
+            api-token: ${{ secrets.MODRINTH_API_TOKEN }}
+            project-id: ${{ vars.MODRINTH_MODPACK_ID }}
+            modpack-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-modrinth.mrpack
+            modpack-server-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
+            changelog: ${{ needs.info.outputs.changelog }}
+            changelog-format: markdown
+            game-version: ${{ needs.info.outputs.mc_version }}
+            display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}
+            server-display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
+            release-type: ${{ needs.info.outputs.release_type }}
 
   release-github:
     name: Deploy to GitHub
@@ -352,20 +350,21 @@ jobs:
       - name: Create release
         uses: softprops/action-gh-release@v2.0.8
         with:
-          prerelease: false
-          generate_release_notes: true
           name: ${{ needs.info.outputs.project_version }}
+          tag_name: 4.5.3
+          # tag_name: ${{ needs.info.outputs.project_version }}
           body: |
             ${{ needs.info.outputs.changelog }}
-            ```${{ needs.info.outputs.diff }}```
+            ```markdown
+            ${{ needs.info.outputs.diff }}
+            ```
           files: |
             ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge.zip
             ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
             ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc.zip
-          tag_name: 4.5.3
-          # tag_name: ${{ needs.info.outputs.project_version }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          prerelease: false
+          generate_release_notes: true
+          token: ${{ secrets.GITHUB_TOKEN }}
 
   discord-message:
     name: Discord Message
@@ -385,5 +384,7 @@ jobs:
             **Game Version**: `${{ needs.info.outputs.mc_version }}`
             [CurseForge](https://www.curseforge.com/minecraft/modpacks/terrafirmagreg/files/${{ needs.release-curseforge.outputs.id }}) • [GitHub](https://github.com/${{ github.repository }}/releases/tag/${{ needs.info.outputs.project_version }}) • [Issues](https://github.com/${{ github.repository }}/issues)
 
-            ```${{ needs.info.outputs.changelog }}```
+            ```markdown
+            ${{ needs.info.outputs.changelog }}
+            ```
             ** [Read more...](https://github.com/${{ github.repository }}/releases/tag/${{ needs.info.outputs.project_version }}) **
