ops

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,12 +20,11 @@ jobs:
   info:
     name: Project Info
     runs-on: ubuntu-latest
-
     outputs:
       project_version: ${{ steps.project_version.outputs.tag }}
       project_name: ${{ steps.project_name.outputs.value }}
       changelog: ${{ steps.changelog.outputs.description }}
-      diff: ${{ steps.lockfile.outputs.diff }}
+      diff: ${{ steps.diff.outputs.description }}
       release_type: ${{ env.RELEASE_TYPE }}
       mc_version: ${{ env.MC_VERSION }}
     
@@ -95,6 +94,12 @@ jobs:
         uses: coditory/changelog-parser@v1.0.2
         with:
           path: CHANGELOG.md
+
+      - name: Diff Parser
+        id: diff
+        uses: coditory/changelog-parser@v1.0.2
+        with:
+          path: PROJECTS_DIFF.md
           
       - name: Generate list using Markdown
         run: |
@@ -158,223 +163,210 @@ jobs:
           path: ./build/modrinth/${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-modrinth.mrpack
           if-no-files-found: warn
 
-  build-server:
-    name: Build Server Pack
-    runs-on: ubuntu-latest
-    needs: [info]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4.2.2
+  # build-server:
+  #   name: Build Server Pack
+  #   runs-on: ubuntu-latest
+  #   needs: [info]
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4.2.2
 
-      - name: Replace strings
-        shell: bash
-        run: |
-          set +e
+  #     - name: Replace strings
+  #       shell: bash
+  #       run: |
+  #         set +e
 
-          grooovy="./groovy/runConfig.json"
-          cat <<< $(jq '.debug = false' $grooovy) > $grooovy
-          sed -i -e "s/DEV/${{ needs.info.outputs.project_version }}/g" pakku.json
+  #         grooovy="./groovy/runConfig.json"
+  #         cat <<< $(jq '.debug = false' $grooovy) > $grooovy
+  #         sed -i -e "s/DEV/${{ needs.info.outputs.project_version }}/g" pakku.json
 
-      - name: Cache pakku
-        uses: actions/cache@v4.1.2
-        with:
-          path: build/.cache
-          key: ${{ runner.OS }}-pakku-cache-${{ hashFiles('build/.cache/') }}
-          restore-keys: |
-            ${{ runner.OS }}-pakku-cache-
+  #     - name: Cache pakku
+  #       uses: actions/cache@v4.1.2
+  #       with:
+  #         path: build/.cache
+  #         key: ${{ runner.OS }}-pakku-cache-${{ hashFiles('build/.cache/') }}
+  #         restore-keys: |
+  #           ${{ runner.OS }}-pakku-cache-
 
-      - name: Export modpack
-        run: |
-          mv -vf ./.pakku/server-overrides/* ./
-          java -jar ./pakku.jar export
+  #     - name: Export modpack
+  #       run: |
+  #         mv -vf ./.pakku/server-overrides/* ./
+  #         java -jar ./pakku.jar export
 
-      - name: Rename artifact server
-        run: |
-          cd ./build/serverpack/
-          mv *.zip $(basename -s .zip *.zip)-serverpack.zip
+  #     - name: Rename artifact server
+  #       run: |
+  #         cd ./build/serverpack/
+  #         mv *.zip $(basename -s .zip *.zip)-serverpack.zip
 
-      - name: Upload artifact server
-        uses: actions/upload-artifact@v4.4.0
-        with:
-          name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
-          path: ./build/serverpack/${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
-          if-no-files-found: error
+  #     - name: Upload artifact server
+  #       uses: actions/upload-artifact@v4.4.0
+  #       with:
+  #         name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
+  #         path: ./build/serverpack/${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
+  #         if-no-files-found: error
 
-  build-multimc:
-    name: Build MultiMC Pack
-    runs-on: ubuntu-latest
-    needs: [info]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4.2.2
+  # build-multimc:
+  #   name: Build MultiMC Pack
+  #   runs-on: ubuntu-latest
+  #   needs: [info]
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4.2.2
 
-      - name: Replace strings
-        shell: bash
-        run: |
-          set +e
+  #     - name: Replace strings
+  #       shell: bash
+  #       run: |
+  #         set +e
 
-          grooovy="./groovy/runConfig.json"
-          cat <<< $(jq '.debug = false' $grooovy) > $grooovy
+  #         grooovy="./groovy/runConfig.json"
+  #         cat <<< $(jq '.debug = false' $grooovy) > $grooovy
 
-      - name: Cache pakku
-        uses: actions/cache@v4.1.2
-        with:
-          path: build/.cache
-          key: ${{ runner.OS }}-pakku-cache-${{ hashFiles('build/.cache/') }}
-          restore-keys: |
-            ${{ runner.OS }}-pakku-cache-
+  #     - name: Cache pakku
+  #       uses: actions/cache@v4.1.2
+  #       with:
+  #         path: build/.cache
+  #         key: ${{ runner.OS }}-pakku-cache-${{ hashFiles('build/.cache/') }}
+  #         restore-keys: |
+  #           ${{ runner.OS }}-pakku-cache-
 
-      - name: Export
-        run: |
-          java -jar pakku.jar --debug fetch
-          java -jar pakku.jar --debug export
+  #     - name: Export
+  #       run: |
+  #         java -jar pakku.jar --debug fetch
+  #         java -jar pakku.jar --debug export
           
-      - name: Move files
-        run: |
-          ls
-          mkdir -p .pakku/multimc-overrides/flame
-          mv -vf ./build/.cache/curseforge/manifest.json .pakku/multimc-overrides/flame/manifest.json
-          mv -vf ./build/.cache/curseforge/overrides .pakku/multimc-overrides/.minecraft
-          mv -vf ./mods .pakku/multimc-overrides/.minecraft/mods
-          cd .pakku/multimc-overrides/
+  #     - name: Move files
+  #       run: |
+  #         ls
+  #         mkdir -p .pakku/multimc-overrides/flame
+  #         mv -vf ./build/.cache/curseforge/manifest.json .pakku/multimc-overrides/flame/manifest.json
+  #         mv -vf ./build/.cache/curseforge/overrides .pakku/multimc-overrides/.minecraft
+  #         mv -vf ./mods .pakku/multimc-overrides/.minecraft/mods
+  #         cd .pakku/multimc-overrides/
           
-          zip -r ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc.zip icon.png mmc-pack.json instance.cfg .minecraft/ flame/
+  #         zip -r ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc.zip icon.png mmc-pack.json instance.cfg .minecraft/ flame/
       
-      - name: Upload zip multimc
-        uses: actions/upload-artifact@v4.4.0
-        with:
-          name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc
-          path: .pakku/multimc-overrides/${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc.zip
-          if-no-files-found: error
+  #     - name: Upload zip multimc
+  #       uses: actions/upload-artifact@v4.4.0
+  #       with:
+  #         name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc
+  #         path: .pakku/multimc-overrides/${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc.zip
+  #         if-no-files-found: error
 
-  release:
-    name: Release
-    needs: [info, build-modpack, build-server, build-multimc]
-    uses: ./.github/workflows/release.yml
-    with:
-      project_name: ${{ needs.info.outputs.project_name }}
-      project_version: ${{ needs.info.outputs.project_version }}
-      release_type: ${{ needs.info.outputs.release_type }}
-      mc_version: ${{ needs.info.outputs.mc_version }}
-      changelog: ${{ needs.info.outputs.changelog }}
-      diff: ${{ needs.info.outputs.diff }}
-    secrets: inherit
+  # release-curseforge:
+  #   name: Deploy to CurseForge
+  #   needs: [info, build-modpack, build-server]
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     id: ${{ steps.cf_release.outputs.id }}
+  #   steps:
+  #     - name: Check if CF_API_TOKEN exist
+  #       shell: bash
+  #       run: |
+  #         if [ "${{ secrets.CF_API_TOKEN }}" == '' ]; then
+  #           echo '::error::No value found for secret key `CF_API_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+  #         fi  
 
-  release-curseforge:
-    name: Deploy to CurseForge
-    needs: [info, build-modpack, build-server]
-    runs-on: ubuntu-latest
-    outputs:
-      id: ${{ steps.cf_release.outputs.id }}
-    steps:
-      - name: Check if CF_API_TOKEN exist
-        shell: bash
-        run: |
-          if [ "${{ secrets.CF_API_TOKEN }}" == '' ]; then
-            echo '::error::No value found for secret key `CF_API_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
-          fi  
+  #     - name: Download artifact curseforge
+  #       uses: actions/download-artifact@v4.1.8
+  #       with:
+  #         name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge
 
-      - name: Download artifact curseforge
-        uses: actions/download-artifact@v4.1.8
-        with:
-          name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge
+  #     - name: Download artifact server
+  #       uses: actions/download-artifact@v4.1.8
+  #       with:
+  #         name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
 
-      - name: Download artifact server
-        uses: actions/download-artifact@v4.1.8
-        with:
-          name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
+  #     - name: Upload Curseforge
+  #       id: cf_release
+  #       uses: Xikaro/upload-curseforge-modpack-action@1.1.1
+  #       with:
+  #         api-token: ${{ secrets.CF_API_TOKEN }}
+  #         project-id: ${{ vars.CF_MODPACK_ID }}
+  #         display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}
+  #         modpack-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge.zip
+  #         server-display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
+  #         modpack-server-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
+  #         changelog: ${{ needs.info.outputs.changelog }}
+  #         changelog-format: markdown
+  #         game-version: ${{ needs.info.outputs.mc_version }}
+  #         release-type: ${{ needs.info.outputs.release_type }}
 
-      - name: Upload Curseforge
-        id: cf_release
-        uses: Xikaro/upload-curseforge-modpack-action@1.1.1
-        with:
-          api-token: ${{ secrets.CF_API_TOKEN }}
-          project-id: ${{ vars.CF_MODPACK_ID }}
-          display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}
-          modpack-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge.zip
-          server-display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
-          modpack-server-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
-          changelog: ${{ needs.info.outputs.changelog }}
-          changelog-format: markdown
-          game-version: ${{ needs.info.outputs.mc_version }}
-          release-type: ${{ needs.info.outputs.release_type }}
-
-  release-modrinth:
-      name: Deploy to Modrinth
-      needs: [info, build-modpack, build-server]
-      runs-on: ubuntu-latest
-      steps:
-        - name: Check if MODRINTH_API_TOKEN exist
-          shell: bash
-          run: |
-            if [ "${{ secrets.MODRINTH_API_TOKEN }}" == '' ]; then
-              echo '::error::No value found for secret key `MODRINTH_API_TOKEN`. See https://docs.github.com/en/  actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
-            fi  
+  # release-modrinth:
+  #     name: Deploy to Modrinth
+  #     needs: [info, build-modpack, build-server]
+  #     runs-on: ubuntu-latest
+  #     steps:
+  #       - name: Check if MODRINTH_API_TOKEN exist
+  #         shell: bash
+  #         run: |
+  #           if [ "${{ secrets.MODRINTH_API_TOKEN }}" == '' ]; then
+  #             echo '::error::No value found for secret key `MODRINTH_API_TOKEN`. See https://docs.github.com/en/  actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+  #           fi  
     
-        - name: Download artifact modrinth
-          uses: actions/download-artifact@v4.1.8
-          with:
-            name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-modrinth
+  #       - name: Download artifact modrinth
+  #         uses: actions/download-artifact@v4.1.8
+  #         with:
+  #           name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-modrinth
     
-        - name: Download artifact server
-          uses: actions/download-artifact@v4.1.8
-          with:
-            name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
+  #       - name: Download artifact server
+  #         uses: actions/download-artifact@v4.1.8
+  #         with:
+  #           name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
     
-        - name: Upload Modrinth
-          id: cf_release
-          uses: Xikaro/upload-curseforge-modpack-action@1.1.1
-          with:
-            api-token: ${{ secrets.MODRINTH_API_TOKEN }}
-            project-id: ${{ vars.MODRINTH_MODPACK_ID }}
-            modpack-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-modrinth.mrpack
-            modpack-server-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
-            changelog: ${{ needs.info.outputs.changelog }}
-            changelog-format: markdown
-            game-version: ${{ needs.info.outputs.mc_version }}
-            display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}
-            server-display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
-            release-type: ${{ needs.info.outputs.release_type }}
+  #       - name: Upload Modrinth
+  #         id: cf_release
+  #         uses: Xikaro/upload-curseforge-modpack-action@1.1.1
+  #         with:
+  #           api-token: ${{ secrets.MODRINTH_API_TOKEN }}
+  #           project-id: ${{ vars.MODRINTH_MODPACK_ID }}
+  #           modpack-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-modrinth.mrpack
+  #           modpack-server-path: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
+  #           changelog: ${{ needs.info.outputs.changelog }}
+  #           changelog-format: markdown
+  #           game-version: ${{ needs.info.outputs.mc_version }}
+  #           display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}
+  #           server-display-name: ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack
+  #           release-type: ${{ needs.info.outputs.release_type }}
 
-  release-github:
-    name: Deploy to GitHub
-    needs: [info, build-modpack, build-server, build-multimc]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4.2.2
+  # release-github:
+  #   name: Deploy to GitHub
+  #   needs: [info, build-modpack, build-server, build-multimc]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4.2.2
 
-      - name: Download artifact
-        uses: actions/download-artifact@v4.1.8
-        with:
-          merge-multiple: true
+  #     - name: Download artifact
+  #       uses: actions/download-artifact@v4.1.8
+  #       with:
+  #         merge-multiple: true
 
-      - name: Сlose fixed in dev
-        uses: Xikaro/close-issues-based-on-label@master
-        env:
-          LABEL: "2. Status: In Dev"
-          COMMENT: In ${{ needs.info.outputs.project_version }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Сlose fixed in dev
+  #       uses: Xikaro/close-issues-based-on-label@master
+  #       env:
+  #         LABEL: "2. Status: In Dev"
+  #         COMMENT: In ${{ needs.info.outputs.project_version }}
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Create release
-        uses: softprops/action-gh-release@v2.0.8
-        with:
-          prerelease: false
-          generate_release_notes: true
-          name: ${{ needs.info.outputs.project_version }}
-          body: |
-            ${{ needs.info.outputs.changelog }}
-            ${{ needs.info.outputs.diff }}
-          files: |
-            ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge.zip
-            ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
-            ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc.zip
-          tag_name: 4.5.3
-          # tag_name: ${{ needs.info.outputs.project_version }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Create release
+  #       uses: softprops/action-gh-release@v2.0.8
+  #       with:
+  #         prerelease: false
+  #         generate_release_notes: true
+  #         name: ${{ needs.info.outputs.project_version }}
+  #         body: |
+  #           ${{ needs.info.outputs.changelog }}
+  #           ${{ needs.info.outputs.diff }}
+  #         files: |
+  #           ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-curseforge.zip
+  #           ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-serverpack.zip
+  #           ${{ needs.info.outputs.project_name }}-${{ needs.info.outputs.project_version }}-multimc.zip
+  #         tag_name: 4.5.3
+  #         # tag_name: ${{ needs.info.outputs.project_version }}
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  discord-message:
+  # discord-message:
     name: Discord Message
     needs: [info, release-github]
     runs-on: ubuntu-latest
