workflows backport

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,91 +1,156 @@
-name: Deploy modpack
+name: Release
+run-name: "Release #${{ github.run_number }}"
 
 on:
-  push:
-    tags:
-      - "*.*.*"
+  workflow_call:
+    inputs:
+      project_name:
+        required: true
+        type: string
+      project_version:
+        required: true
+        type: string
+      mc_version:
+        required: true
+        type: string
+      changelog:
+        required: true
+        type: string
+
+env:
+  CF_PROJECT_ID: "385053"
+  MODRINTH_PROJECT_ID: "75JuuMzk"
+  RELEASE_TYPE: "BETA"
 
 jobs:
-  Deploy:
+  release-curseforge:
+    name: Deploy to CurseForge
     runs-on: ubuntu-latest
+    steps:
+      - name: Check if CF_API_TOKEN exist
+        shell: bash
+        run: |
+          if [ "${{ secrets.CF_API_TOKEN }}" == '' ]; then
+            echo '::error::No value found for secret key `CF_API_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+          fi  
+
+      - name: Download cf modpack
+        uses: actions/download-artifact@v4.1.0
+        with:
+          name: ${{ inputs.project_name }}-${{ inputs.project_version }}-cf
+
+      - name: Download serverpack
+        uses: actions/download-artifact@v4.1.0
+        with:
+          name: ${{ inputs.project_name }}-${{ inputs.project_version }}-server
+
+      - name: Upload Curseforge
+        id: cf_release
+        uses: SwitchAlpha/upload-curseforge-modpack-action@master
+        with:
+          api-token: ${{ secrets.CF_API_TOKEN }}
+          project-id: ${{ env.CF_PROJECT_ID }}
+          modpack-path: ${{ inputs.project_name }}-${{ inputs.project_version }}-cf.zip
+          modpack-server-path: ${{ inputs.project_name }}-${{ inputs.project_version }}-server.zip
+          changelog: ${{ inputs.changelog }}
+          changelog-format: markdown
+          game-version: ${{ inputs.mc_version }}
+          display-name: ${{ inputs.project_name }}-${{ inputs.project_version }}
+          server-display-name: ${{ inputs.project_name }}-${{ inputs.project_version }}-server
+          release-type: ${{ env.RELEASE_TYPE }}
+
+      - name: Send Discord message
+        uses: tsickert/discord-webhook@v5.4.0
+        with:
+          webhook-url: ${{secrets.RELEASES_1_12}}
+          username: "TerraFirmaGreg"
+          avatar-url: "https://raw.githubusercontent.com/TerraFirmaGreg-Team/.github/main/branding/curseforge_logo.png"
+          embed-title: Release ${{ inputs.project_version }}
+          embed-url: https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.12.x/releases/tag/${{ inputs.project_version }}
+          embed-thumbnail-url: https://raw.githubusercontent.com/TerraFirmaGreg-Team/.github/main/branding/logo_new_year.png
+          embed-description: |
+            **Release Type**: `${{ env.RELEASE_TYPE }}`
+            **GameVersion**: `${{ inputs.mc_version }}`
+            **Website Link**: [CurseForge](https://www.curseforge.com/minecraft/modpacks/terrafirmagreg/files/${{ steps.cf_release.outputs.id }})
+
+            **Changelog**
+            ```${{ inputs.changelog }}```
+          embed-color: 5814783
+
+  release-github:
+    name: Deploy to GitHub
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download modpack
+        uses: actions/download-artifact@v4.1.0
+        with:
+          merge-multiple: true
+
+      - name: Create release
+        uses: softprops/action-gh-release@v1
+        with:
+          prerelease: false
+          generate_release_notes: true
+          name: ${{ inputs.project_version }}
+          body: ${{ inputs.CHANGELOG }}
+          files: |
+            ${{ inputs.project_name }}-${{ inputs.project_version }}-cf.zip
+            ${{ inputs.project_name }}-${{ inputs.project_version }}-mmc.zip
+            ${{ inputs.project_name }}-${{ inputs.project_version }}-server.zip
+          tag_name: ${{ inputs.project_version }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  # release-modrinth:
+  #   name: Deploy to Modrinth
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check if MODRINTH_API_TOKEN exist
+  #       shell: bash
+  #       run: |
+  #         if [ "${{ secrets.MODRINTH_API_TOKEN }}" == '' ]; then
+  #           echo '::error::No value found for secret key `MODRINTH_API_TOKEN`. See https://docs.github.com/en/actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+  #         fi  
+
+  #     - name: Download modpack
+  #       uses: actions/download-artifact@v4.1.0
+  #       with:
+  #         name: modpack_mrd
+
+  #     - name: Download serverpack
+  #       uses: actions/download-artifact@v4.1.0
+  #       with:
+  #         name: server_pack
+
+  #     - name: Upload Modrinth
+  #       id: cf_release
+  #       uses: SwitchAlpha/upload-curseforge-modpack-action@master
+  #       with:
+  #         api-token: ${{ secrets.MODRINTH_API_TOKEN }}
+  #         project-id: ${{ env.MODRINTH_PROJECT_ID }}
+  #         modpack-path: ${{ inputs.project_name }}-${{ inputs.project_version }}-mrd.zip
+  #         modpack-server-path: ${{ inputs.project_name }}-${{ inputs.project_version }}-server.zip
+  #         changelog: "${{ inputs.CHANGELOG }}"
+  #         changelog-format: markdown
+  #         game-version: ${{ inputs.mc_version }}
+  #         display-name: ${{ inputs.project_name }}-${{ inputs.project_version }}
+  #         server-display-name: ${{ inputs.project_name }}-${{ inputs.project_version }}-server
+  #         release-type: ${{ env.RELEASE_TYPE }}
+
+  close-fixed-issues:
+    name: Close Fixed Issues
+    runs-on: ubuntu-latest
+    needs: [release-github, release-curseforge]
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.1
 
-      - name: Get the version
-        id: get_version
-        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
+      - name: close-fixed-in-dev
+        uses: juraj-hrivnak/close-issues-based-on-label@master
+        env:
+          LABEL: "2. Status: Fixed in Dev"
+          VERSION: ${{ inputs.project_version }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Changelog Parser
-        id: changelog
-        uses: coditory/changelog-parser@v1.0.2
-        with:
-          path: CHANGELOG.md
+      
 
-      - name: Set the version
-        run: |
-          DEV=${{ steps.get_version.outputs.version }}
-          sed -i -e "s/DEV/${DEV}/g" manifest.json
-          sed -i -e "s/DEV/${DEV}/g" instance.cfg
-          sed -i -e "s/DEV/${DEV}/g" groovy/runConfig.json
-          sed -i -e "s/DEV/${DEV}/g" config/fancymenu/customization/tfg_version.txt
-
-      - name: Move
-        run: |
-          rsync -av --exclude-from='.github/buildtools/filelist.txt' ./ .minecraft/
-
-      - name: Archive MMC
-        run: |
-          zip -r ./TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}-mmc.zip mmc-pack.json instance.cfg .minecraft/
-
-      - name: Archive CF
-        run: |
-          mv -vf .minecraft/ overrides/ 
-          zip -r ./TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}-cf.zip manifest.json modlist.html overrides/bansoukou/ overrides/resourcepacks/ overrides/config/ overrides/groovy/ overrides/scripts/
-
-      - name: Archive Server
-        run: |
-          cp -r .github/buildtools/serverfiles/* overrides/
-          cat .github/buildtools/client_mod.txt | while read -r line; do find overrides/mods -name "$line" -delete; done
-          rm -rf overrides/resourcepacks overrides/config/txloader
-          cd overrides/
-          zip -r ../TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}-server.zip ./
-
-      - name: Upload Curseforge
-        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
-        with:
-          api-token: ${{ secrets.CF_API_TOKEN }}
-          project-id: "385053"
-          modpack-path: ./TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}-cf.zip
-          modpack-server-path: ./TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}-server.zip
-          changelog: "${{ steps.changelog.outputs.description }}"
-          changelog-format: markdown
-          game-version: "1.12.2"
-          display-name: TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}
-          server-display-name: TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}-server
-          release-type: "release"
-
-      - name: Create GitHub Release
-        uses: softprops/action-gh-release@v0.1.15
-        if: startsWith(github.ref, 'refs/tags/')
-        with:
-          prerelease: false
-          generate_release_notes: true
-          name: Release ${{ steps.changelog.outputs.version }}
-          body: ${{ steps.changelog.outputs.description }}
-          files: |
-            ./TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}-cf.zip
-            ./TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}-mmc.zip
-            ./TerraFirmaGreg-1.12-${{ steps.get_version.outputs.version }}-server.zip
-
-      - name: Discord notification
-        uses: tsickert/discord-webhook@v5.3.0
-        with:
-          webhook-url: ${{ secrets.RELEASES_1_12 }}
-          username: "GitHub"
-          avatar-url: https://github.com/TerraFirmaGreg-Team/.github/blob/6279c7b205e642fd6b1398f55df988dfd306d265/branding/logo.png
-          embed-title: Release ${{ steps.changelog.outputs.version }}
-          embed-description: "${{ steps.changelog.outputs.description }}"
-          embed-url: https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.12.x/tree/main/CHANGELOG.md
-          embed-color: 15430476
-          embed-footer-text: ${{ steps.changelog.outputs.date }}
